### PR TITLE
Add Shell Profiles and Fix Pre-Commit 

### PR DESCRIPTION
**Pull request by apanzerj**
Add support for shell profiles into this module.

### CODE REVIEW

**Comment by JamesWoolfenden** [comment]
If you merge with the latest ill take a look at adding the profiles.

**Comment by apanzerj** [comment]
@JamesWoolfenden Done!

**Comment by apanzerj** [comment]
(I'll take a look at the other PR and see if I can add more of it too, I just need a bit to fix other stuff I'm working on)

**Comment by apanzerj** [comment]
@JamesWoolfenden I made a go at the other PR and doing a rebase but the code fails several checkov rules and I'm not actually going to use any of the features it builds on that this PR isn't already implementing. Any chance I can get a review when you have a minute?

**Comment by JamesWoolfenden** [comment]
LGTM not sure whats going on that other PR but this one seems fine

**Comment by JamesWoolfenden** [comment]
thanks for the contribution!

**Comment by apanzerj** [comment]
Woot thanks!

**Pull request merged**
